<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<?php /** @var $viewModel \Skywire\OutdatedBrowserBanner\ViewModel\Banner */ ?>
<?php $viewModel = $block->getViewModel() ?>
<a href="https://updatemybrowser.org/" target="_blank" class="sw-browser-warning" id="sw-browser-warning" aria-label="Outdated Browser Warning">
    <span class="sw-browser-warning__inner">
        <p class="sw-browser-warning__text">It looks like you are still using an browser that is no longer supported with security updates. Some features on this site may not work including the checkout. We strongly recommend that you either update your browser or use another one such as:</p>

        <span class="sw-browser-warning__browser">
            <span class="sw-browser-warning__icon sw-browser-warning__icon--chrome"></span>
            Google Chrome
        </span>
        <span class="sw-browser-warning__browser">
            <span class="sw-browser-warning__icon sw-browser-warning__icon--edge"></span>
            Microsoft Edge
        </span>
        <span class="sw-browser-warning__browser">
            <span class="sw-browser-warning__icon sw-browser-warning__icon--firefox"></span>
            Firefox
        </span>
        <span class="sw-browser-warning__browser">
            <span class="sw-browser-warning__icon sw-browser-warning__icon--safari"></span>
            Safari
        </span>
    </span>
</a>
<script>
    try {
        var SWisIE11 = SWdetectIE();

        function SWdetectIE(uaString) {
            uaString = uaString || navigator.userAgent;
            var match = /\b(MSIE |Trident.*?rv:|Edge\/)(\d+)/.exec(uaString);
            if (match) return parseInt(match[2])
        }

        // var SWisIE11 = '-ms-scroll-limit' in document.documentElement.style && '-ms-ime-align' in document.documentElement.style;
        if (SWisIE11 <= 11) {
            document.getElementById("sw-browser-warning").style.display = 'block';
        } else {
            document.getElementById("sw-browser-warning").classList.add("sw-browser-ok");
        }
    } catch (e) {
        console.log('SWdetectIE broken: ' + e.message)
    }
</script>
